---

- name: Import Elasticsearch Key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Download Elastichsearch 5.1
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.rpm
    dest: /tmp/
    force: no

- name: Install Elastichsearch via RPM file with yum
  yum:
    name: "/tmp/elasticsearch-5.1.1.rpm"
    state: present
