---

- name: Add Syslog Server Domain Name and IP address to Server Hosts File
  lineinfile:
    backup: yes
    dest: /etc/hosts
    line: "{{syslogng_server_ip }} {{ syslogng_dn_prefix }}.{{ syslogng_dn_suffix }}"

