---

- name: Download Kibana 5.1
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-5.1.1-x86_64.rpm
    dest: /tmp/
    force: no

- name: Install Kibana via RPM file with yum
  yum:
    name: "/tmp/kibana-5.1.1-x86_64.rpm"
    state: present

- name: Configure Server Port for Kibana
  replace:
    path: '/etc/kibana/kibana.yml'
    regexp: '#server.port: 5601'
    replace: 'server.port: 5601'
    backup: yes

- name: Configure Server Host for Kibana
  replace:
    path: '/etc/kibana/kibana.yml'
    regexp: '#server.host: "localhost"'
    replace: 'server.host: "localhost"'
    backup: yes

- name: Configure Elasticsearch URL for Kibana
  replace:
    path: '/etc/kibana/kibana.yml'
    regexp: '#elasticsearch.url: "http://localhost:9200"'
    replace: 'elasticsearch.url: "http://localhost:9200"'
    backup: yes

- name: Enable Kibana
  systemd:
    name: kibana
    daemon_reload: yes
    enabled: yes

- name: Start Kibana
  systemd:
    name: kibana
    state: started

- name: Set SElinux flag to ON for httpd_can_network_connect 
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
