---

- name: Download Logstash 5.1
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-5.1.1.rpm
    dest: /tmp/
    force: no

- name: Install Logstash via RPM file with yum
  yum:
    name: "/tmp/logstash-5.1.1.rpm"
    state: present

- replace:
    path: /etc/pki/tls/openssl.cnf
    regexp: '^# Extensions for a typical CA'
    replace: |
      # Extensions for a typical CA

      subjectAltName = IP: {{ elk_server_ip }}

    backup: yes

- name: Generate a self-signed cert.
  become: true
  command: >
     openssl req -config /etc/pki/tls/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt

- name: Insert Filebeat Input Config Template
  template:
    src: filebeat-input.conf.j2
    dest: /etc/logstash/conf.d/filebeat-input.conf
    mode: 0644
    owner: root
    group: wheel
    backup: yes

- name: Insert Syslog Filter Config Template
  template:
    src: syslog-filter.conf.j2
    dest: /etc/logstash/conf.d/syslog-filter.conf
    mode: 0644
    owner: root
    group: wheel
    backup: yes

- name: Insert Elastichsearch Output Config Template
  template:
    src: output-elasticsearch.conf.j2
    dest: /etc/logstash/conf.d/output-elasticsearch.conf
    mode: 0644
    owner: root
    group: wheel
    backup: yes

- name: Enable Logstash
  systemd:
    name: logstash
    daemon_reload: yes
    enabled: yes

- name: Start Logstash
  systemd:
    name: logstash
    state: started


